/** Independent persisted-file audit, using the installed runtime decoder. */
import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {MeshoptDecoder} from 'three-stdlib';
const hash=b=>createHash('sha256').update(b).digest('hex');
function parse(b){assert.equal(b.readUInt32LE(0),0x46546c67);assert.equal(b.readUInt32LE(4),2);assert.equal(b.readUInt32LE(8),b.length);let doc,bin;for(let p=12;p<b.length;){const size=b.readUInt32LE(p),type=b.readUInt32LE(p+4);assert.equal(size%4,0);assert(p+8+size<=b.length);if(type===0x4e4f534a)doc=JSON.parse(b.subarray(p+8,p+8+size));if(type===0x004e4942)bin=b.subarray(p+8,p+8+size);p+=8+size;}assert(doc&&bin);return{doc,bin};}
const decoder=typeof MeshoptDecoder==='function'?MeshoptDecoder():MeshoptDecoder;await decoder.ready;
const report=JSON.parse(await readFile('verification/world-optimization-report.json','utf8'));const checks=[];
for(const model of report.models){const bytes=await readFile(model.output),original=await readFile(`asset/${model.number}.glb`);assert.equal(hash(original),model.sourceSha256);assert.equal(hash(bytes),model.outputSha256);const {doc,bin}=parse(bytes),src=parse(original).doc;assert.deepEqual(doc.nodes,src.nodes);assert.deepEqual(doc.materials,src.materials);assert.deepEqual(doc.textures,src.textures);const decoded=[];let compressedViews=0;
for(const view of doc.bufferViews){let value;const e=view.extensions?.EXT_meshopt_compression;if(e){assert.equal(e.buffer,0);assert.equal(view.byteLength,e.count*e.byteStride);assert(e.byteOffset+e.byteLength<=bin.length);value=Buffer.alloc(view.byteLength);decoder.decodeGltfBuffer(value,e.count,e.byteStride,bin.subarray(e.byteOffset,e.byteOffset+e.byteLength),e.mode,e.filter??'NONE');compressedViews++;}else{assert.equal(view.buffer,0);assert((view.byteOffset??0)+view.byteLength<=bin.length);value=bin.subarray(view.byteOffset??0,(view.byteOffset??0)+view.byteLength);}decoded.push(value);}
let triangles=0,vertices=0;for(const mesh of doc.meshes)for(const p of mesh.primitives){const a=doc.accessors[p.indices],pa=doc.accessors[p.attributes.POSITION];assert.equal(a.componentType,5125);assert.equal(a.count%3,0);const ib=decoded[a.bufferView];for(let k=0;k<a.count;k++)assert(ib.readUInt32LE((a.byteOffset??0)+k*4)<pa.count);triangles+=a.count/3;vertices+=pa.count;for(const name of ['POSITION','NORMAL','TEXCOORD_0']){const aa=doc.accessors[p.attributes[name]],b=decoded[aa.bufferView];assert.equal(aa.count,pa.count);assert.equal(aa.componentType,5126);for(let k=0;k<b.length;k+=4)assert(Number.isFinite(b.readFloatLE(k)));}}
assert.equal(triangles,model.triangles);assert.equal(vertices,model.vertices);const textureResolution=doc.images.map(image=>{assert.equal(image.mimeType,'image/png');const b=decoded[image.bufferView];assert.equal(b.subarray(0,8).toString('hex'),'89504e470d0a1a0a');const size=[b.readUInt32BE(16),b.readUInt32BE(20)];assert.deepEqual(size,[2048,2048]);return size;});assert.equal(doc.materials.length,1);assert.equal(doc.images.length,3);checks.push({id:model.id,sourceHashUnchanged:true,finalHashMatches:true,triangles,vertices,materials:doc.materials.length,textures:doc.images.length,textureResolution,compressedViews,decodedIndicesValid:true,finiteGeometryAttributes:true,nodeTransformsUnchanged:true,materialDefinitionsUnchanged:true});}
await writeFile('verification/world-models/independent-validation.json',JSON.stringify({passed:true,decoder:'three-stdlib MeshoptDecoder',checks},null,2)+'\n');console.log(JSON.stringify({passed:true,models:checks.length,totalTriangles:checks.reduce((a,b)=>a+b.triangles,0)}));
